### PR TITLE
Handle foreign keys and indices properly in SQLite and add e2e tests

### LINKED ISSUE #92: Migrations are not idempotent and cause critical divergence between applies
This is a follow up to #91. Upon further debugging, I have made the observation that instead of translating fizz migrations 1:1 to SQL statements, pop/fizz tries to be smart and bundles together the SQL statements, creating one SQL "file" that has "optimizations" (such as removing alter tables in favor of just creating the table). This of course is very bad because if bugs (such as #91) happen, they actually depend on the existing state of the database. For example, a fresh database is missing the foreign key while a database with migrations partially applied does not.

Another serious issue is that fixing bugs like #91 in fizz will cause divergence of databases because new databases (without any existing state) will properly create the foreign key, while older databases (with the buggy statement) will not. Bringing them into line is basically a huge trial and error/guessing game based on what SQL statements are used when and where and how and what database has already had which migrations applied.

I can not state enough that this is really bad for any system that aims to have reliable SQL migrations - so far that we are definitely going to have to switch to raw SQL and tell our users to level their existing database because there's too much complexity involved in fixing all these nuances.

But there is a path forward in my opinion: Fizz (or pop) should use the fizz templates to generate SQL files for each database, which then should be checked into version control and be applied by the migration logic instead of using fizz on-the-fly. This means that fizz would basically become a CLI command that could be used with e.g. `go generate` along the lines of:

```
fizz migrations/*.fizz sql_migration_output/
```

That would then be a directory along the lines of:

- sql_migration_output
  - 123123_myfizzmigration.mysql.sql
  - 123123_myfizzmigration.postgres.sql
  - 123123_myfizzmigration.sqlite.sql

and so on.

As an intermediate step I would highly encourage to put a big warning in the docs to not use fizz migrations because of these issues. Whatever you do, you will run into this stuff eventually and when you do - and depending on when - you're pretty much fucked, especially if it's another OSS project used by people against many, many databases.

### PR DESCRIPTION
**Pull request by aeneasr**
This patch resolves issues with `change_column` and `drop_column` which previously caused duplicate or missing indices and foreign keys. To prevent future regressions and help debugging,
a new e2e-test pipeline has been added to the project and the CI. Documentation for running the tests has been added to the README.

End-to-end tests currently support MySQL, PostgreSQL, and SQLite and do not yet cover other SQL dialects.

During review, please help ensure that the SQL fixtures are not missing something :)

Closes #92

### CODE REVIEW

**Comment by aeneasr** [comment]
CRDB tests fail because pgx driver is missing, but the important failing test case is this one: https://github.com/gobuffalo/fizz/pull/94/checks?check_run_id=788056231

**Comment by aeneasr** [comment]
What I don't really get, it appears that `fizz.AString` correctly includes the foreign key when using `drop_column` (see [here](https://github.com/gobuffalo/fizz/pull/94/files#diff-9f6e5b39b90e9a79dd429f1dedc7f3c7R372-R382)) but the integration test (actually running the migration) does not include the foreign key. Would be great if I could get some help in understanding why!

**Comment by aeneasr** [comment]
@stanislas-m so, I've added a couple of e2e tests now, and fixed #92 and tests are all passing locally. This is ready for review :)

**Comment by aeneasr** [comment]
The failing CRDB test is unrelated to this changeset, it fails because soda is missing `pgx`. This is because fizz uses pgx on master already for e.g. CockroachDB (because of the meta code). Since `pgx` isn't merged to master in pop, soda fails with this code base. Once `pgx` is merged on master in pop, this test failure should go away.

**Comment by aeneasr** [comment]
`sqlite3` binary is missing on the windows system, any idea how to install it?

**Comment by stanislas-m** [comment]
Chocolatey should be available on Windows, so: `choco install sqlite`

**Comment by aeneasr** [comment]
Yup, that seems to have worked! :)

**Comment by aeneasr** [comment]
I think you need to update the repository required checks because I changed the job to a dedicated job for windows on SQLite (chocolatey is not available on the other systems) - it's still waiting for the old SQLite test

**Comment by aeneasr** [comment]
Ok, figured out how to circumvent that, everything green :)

**Comment by stanislas-m** [comment]
LGTM, thanks!

**Pull request merged**
